// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzmjpkxhwfxutujjgcpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6bWpwa3hod2Z4dXR1ampnY3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NTkzMjEsImV4cCI6MjA1ODEzNTMyMX0.fXgI5j84eoBduPv2ySB_VpWALJauoCVap3kjwcYSyw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);